title: Systems Conference Deadlines # (Maintained by @guilhermecox)
# email: cox@computer.org
description: Countdowns to top Systems conference deadlines
author: Abhishek Das

domain: "deadline.systems"
baseurl: ""

twitter_username: cox
twitter_hashtag: SystemsConferences
github_username: guilhermecox
github_repo: systems-deadlines

markdown: kramdown
ga_id: UA-131034143-1

include: ['_pages']
